### ISSUE TITLE
Bug: Time is reported incorrectly when you press T more than once

### ISSUE THREAD

**Issue by LevFendi** [Crimso777/Factorio-Access#38]

**Comment by EphDoering** [comment]
I think it's reporting the in game time of day correctly such that it'll cycle through 24 hours for each day/night cycle. However, it's kinda like we're in a different timezone, because in vanilla the night day cycle goes as follows:
dusk: 0.25 or 6:00
night: 0.45 or 10:48
morning: 0.55 or 13:12
dawn: 0.75 or 18:00

I imagine the purpose of this feature is to let people know when their solar panels will be producing, but since that cycle can vary with mods I'm not sure the best way to go about announcing it. Maybe something like "nighttime, morning in x minutes"?

**Comment by LevFendi** [comment]
If we end up reporting the solar panel yield from the electricity overview interface, perhaps this time feature would not be needed at all?

Or it can simply report "it is dawn/dusk/day/night time".

**Comment by EphDoering** [comment]
Yeah that's a good point. I usually get my information about how long the
day is and where in the day night cycle it currently is from the graphs on
the electricity grid. I think knowing how far along you are through the
light cycle is pretty important for diagnosing if you need more
accumulators or more solar. I'm trying to think of the best way to convey
the information that I normally get from the solar production plot.
